### ISSUE TITLE
mustache.sh is missing

### ISSUE THREAD

**Issue by tomaadland** [devstructure/blueprint#102]
Try to install this from scratch as described in the install part. 

Meet all the listed requirements listed. But upon running make I get this:

pydir=/usr/local/lib/python2.6/dist-packages mustache.sh/bin/mustache.sh <bin/blueprint-template.mustache >bin/blueprint-template
/bin/sh: mustache.sh/bin/mustache.sh: not found
make: **\* [bin/blueprint-template] Error 127

I can't find this file anywhere in the repository accept for in some commits it looks like it was added in as a submodule that I can't access.

**Comment by rcrowley** [comment]
I'm sorry about that, Tom.  I've updated the submodule to use a public Git repository (that was sloppy on my part) and updated the README with the `git submodule update --init` command.

**Comment by christophermanning** [comment]
That command needs to be added to https://devstructure.com/docs/tutorial.html as well.
