### ISSUE TITLE
blueprint create skipping files

### ISSUE THREAD

**Issue by danielnbarbosa** [devstructure/blueprint#105]
When doing a 'blueprint create' blueprint is skipping several files in a directory.  The directory is under '/etc/httpd/sites-available' and contains a bunch of files representing virtual hosts.  Many of the files have the same timestamp and it is these files that are being skipped.  Changing the timestamp of one of these files causes it to be picked up by 'blueprint create'.

For example, with the below directory listing, only 'site7.com and site9.com' get pulled in.  This doesn't seem to be related to the mtime because upon changing a file back to the exact mtime of the other files it still gets pulled in.  Perhaps ctime?  

-rw-r--r-- 1 root root 2135 Oct 27 09:32 site1.com
-rw-r--r-- 1 root root 1909 Oct 27 09:32 site2.com
-rw-r--r-- 1 root root 1332 Oct 27 09:32 site3.com
-rw-r--r-- 1 root root 2315 Oct 27 09:32 site4.com
-rw-r--r-- 1 root root 2521 Oct 27 09:32 site5.com
-rw-r--r-- 1 root root 1980 Oct 27 09:32 site6.com
-rw-r--r-- 1 root root 2360 Dec  5 14:20 site7.com
-rw-r--r-- 1 root root 1782 Oct 27 09:32 site8.com
-rw-r--r-- 1 root root 3151 Dec 13 16:29 site9.com

**Comment by rcrowley** [comment]
Indeed, Blueprint uses a heuristic on ctime to determine files it thinks it can ignore.  When several files in the same directory share the same ctime, they're ignored.  Adding

```
!/etc/httpd/sites-available
```

to `/etc/blueprintignore` will cause Blueprint to include those files anyway.  See http://devstructure.github.com/blueprint/#ignore for more details.

**Comment by cmer** [comment]
I there a way to simply tell Blueprint to not try to be so smart about this and to include every single file?

I also have a similar issue. My entire /opt directory was ignored, as well as /home.
