### ISSUE TITLE
Supervisor config files not being captured

### ISSUE THREAD

**Issue by jzcoder** [devstructure/blueprint#109]
I'm using Ubuntu 10.04, and our system uses supervisord to manage several background processes. Application specific config files are usually stored under /etc/supervisor/conf.d .  I have two in my environment celeryd.conf and uwsgi.conf, but ideally you collect any under this directory.

**Comment by rcrowley** [comment]
@jzcoder Could you paste in the output of `ls -cl /etc/supervisor/conf.d`?  Those files should be included in the blueprint if they're not members of Debian packages but there are cases where that might not be true, such as sharing the same `ctime`.

**Comment by jzcoder** [comment]
total 12
-rw-r--r-- 1 root root 822 2012-01-10 15:14 celeryd.conf
-rw-r--r-- 1 root root 142 2012-01-10 14:54 README
-rw-r--r-- 1 root root 244 2012-01-10 15:14 uwsgi.conf

**Comment by rcrowley** [comment]
@jzcoder if you `touch /etc/supervisor/conf.d/celeryd.conf` and create a blueprint, are both included?  The ctime heuristic Blueprint uses is important but this is a case in which it falls down.

You can make sure particular files are included in the blueprint by adding `!/etc/supervisor/conf.d` to `/etc/blueprintignore`.
