### ISSUE TITLE
Python virtualenv pip dependencies not archived

### ISSUE THREAD

**Issue by jzcoder** [devstructure/blueprint#110]
Our application is setup in a separate virtualenv environment with quite a few pip installed dependencies. It would be nice if blueprint could somehow capture this.

**Comment by rcrowley** [comment]
Blueprint tries to grab packages from the currently active virtualenv per the `VIRTUAL_ENV` environment variable.  Is that set in your environment after sourcing `bin/activate`?

In general, however, Blueprint encourages users to install things system-wide (using virtual machines or containers for full-stack isolation).

**Comment by jzcoder** [comment]
Thank you. I may not have activated by venv. Which makes sense.  Note: The reason I am using a virtualenv is my ubuntu has a different python interpreter installed (2.6.5) and I want to use (2.7.1) on my application without messing up the OS dependencies.

**Comment by rcrowley** [comment]
That's a totally fair reason to use virtualenv.  I hope that just creating blueprints while the virtualenv is active is enough to solve the problem.
