### ISSUE TITLE
Run local IO server without S3

### ISSUE THREAD

**Issue by silid** [devstructure/blueprint#111]
How can I run a local IO server within our network that doesn't require Amazon S3?

**Comment by zenmatt** [comment]
We're planning to open source IO server shortly and you could modify the storage location. Alternatively we have documentation up at http://devstructure.github.com/blueprint/ outlining what you'd need to write a custom IO server.

**Comment by silid** [comment]
Thanks. I'll look at that.

I've currently opted to try running a Cumulus instance internally.
http://www.nimbusproject.org/doc/nimbus/faq/#what-is-cumulus
