### ISSUE TITLE
generate posix shell code typo

### ISSUE THREAD

**Issue by nestoru** [devstructure/blueprint#112]
It says:
<quote>
Generate POSIX shell code from a blueprint

blueprint show -S my-first-blueprint
</quote>

Shouldn't it say:
blueprint create -S my-first-blueprint

???

Thanks for this work!
-Nestor

**Comment by rcrowley** [comment]
Both `blueprint create -S my-first-blueprint` and `blueprint show -S my-first-blueprint` are valid commands.  `blueprint-create`(1) reverse-engineers the system, stores the result under a name, and then processes optional `-S` (and other) code generation arguments.

Technically, `blueprint create -S my-first-blueprint` is the same as

```
blueprint create my-first-blueprint
blueprint show -S my-first-blueprint
```

Does that help?

**Comment by nestoru** [comment]
I am sorry I understood (incorrectly) that you were describing a way to get a footprint from the box.

BTW it looks like if you have custom installations like /opt/tomcat it will fail to find at least that the directory is not a standard deployment I would say. 

Your work has a great value for standard installations for sure though.

Thanks again for this!
-Nestor
