### ISSUE TITLE
Create blueprint-rules file from a blueprint

### ISSUE THREAD

**Issue by hvisser** [devstructure/blueprint#115]
Currently it's sort of all or nothing: either I use blueprint create and tweak that or I use blueprint-rules to build up the blueprint by hand. It would be nice if there was some sort of way to create a blueprint-rules file from an existing blueprint and tweak that.

There might be a way to do this already, but in that case I'm unaware of it ;)

**Comment by rcrowley** [comment]
Damn good idea, @hvisser

**Comment by hvisser** [comment]
Awesome, thanks!
