### ISSUE TITLE
Pull diffs from remote blueprint by ssh

### ISSUE THREAD

**Issue by pnuzhdin** [devstructure/blueprint#130]
It would be nice if we can pull and install diff from remote blueprint by ssh

**Comment by rcrowley** [comment]
You can already pull via SSH as follows:

```
ssh example.com blueprint show example | blueprint create example
```

Does this, combined with using `blueprint-diff`(1) remotely and `blueprint-apply`(1) locally, suit your purposes?

I agree it would be nice to integrate SSH transport more seamlessly.  I'll think more on it.
