### ISSUE TITLE
Packages missing for Debian Wheezy

### ISSUE THREAD

**Issue by KenMacD** [devstructure/blueprint#145]
Following the install instructions results in:

```
Err http://packages.devstructure.com wheezy/main amd64 Packages
  404  Not Found
```

From manually checking the packages server it looks like there are no pre-built packages for wheezy.

**Comment by anarcat** [comment]
not just wheezy - it seems the whole packages.d.c is gone, here:

http://packages.devstructure.com/jessie/
http://packages.devstructure.com/precise/
http://packages.devstructure.com/trusty/

see also https://github.com/devstructure/blueprint/issues/150

where's the source for the debian packages?

**Comment by rcrowley** [comment]
This project has been abandoned for almost five years.
