### ISSUE TITLE
using blueprint across debian distributions

### ISSUE THREAD

**Issue by ymmark0** [devstructure/blueprint#146]
What the procedure when trying to create new systems and install the appropriate packages?
I have a set of physical servers running debian squeeze.  
I'm creating some new cloud servers running wheezy on rackspace.
I want to use blueprint to make sure that new cloud servers have the same config as the existing physical servers (or perhaps it's not the best tool for this?)

I think that an approach is to upgrade a physical squeeze server to wheezy.  Create a new blueprint, then use that blueprint to add the necessary packages to the wheezy cloud server. Is that correct is is there a better way?
cheers

**Comment by rcrowley** [comment]
I'm sorry for the terribly delayed reply.  I believe using the `--relaxed` option to `blueprint-show`(1) or `blueprint-apply`(1) will let you apply your Squeeze blueprints to Wheezy boxen.
