### ISSUE TITLE
Packages missing for Ubuntu Saucy (13.10)

### ISSUE THREAD

**Issue by Hammit** [devstructure/blueprint#150]
No Raring or Saucy packages for Ubuntu.

**Comment by joaocc** [comment]
Any update on this topic?
If help is needed, I can try to contribute, but would need some starting pointers and directions to get me going.
Thanks

**Comment by Hammit** [comment]
Not yet. I'd suggest looking at the latest Ubuntu .deb package(s) and go from there.
Look to take the existing package and put a newer blueprint inside it, making changes where needed.

**Comment by anarcat** [comment]
what are the latest ubuntu packages? i can't find any of them...

**Comment by rcrowley** [comment]
This project has been abandoned for almost five years.
