### ISSUE TITLE
Diff between two blueprints

### ISSUE THREAD

**Issue by rcrowley** [devstructure/blueprint#22]
https://groups.google.com/forum/#!topic/blueprint-users/gSM3iO94uYY discusses using `blueprint.Blueprint.__sub__` to implement diffing between two blueprints.  The use cases described are driving towards more modular output.  Rather than a single monolithic Puppet manifest, the diff represents the customizations on top of a base state.

Quoting Kal McFate, here's a sample workflow:
- kick and puppet a new system
- `blueprint create base`
- set up system
- `blueprint create serverclass`
- `blueprint diff base serverclass`

**Comment by silopolis** [comment]
hi,

This would make this tool even greater, for sure.
