### ISSUE TITLE
CentOS 5.5 (Final) with Python 2.4 gives errors when installing blueprint

### ISSUE THREAD

**Issue by glennaaldering** [devstructure/blueprint#23]
[root@blueprintcentos blueprint]# cat /etc/redhat-release

CentOS release 5.5 (Final)
[root@blueprintcentos blueprint]# python -V

Python 2.4.3
[root@blueprintcentos blueprint]# make install

install -d /usr/local/bin
install \
bin/blueprint \
bin/blueprint-apply \
bin/blueprint-create \
bin/blueprint-destroy \
bin/blueprint-list \
bin/blueprint-show \
/usr/local/bin/
install -d /usr/lib/python2.4/site-packages/blueprint/
install -m644 \
blueprint/chef.py \
blueprint/context_managers.py \
blueprint/git.py \
blueprint/**init**.py \
blueprint/manager.py \
blueprint/puppet.py \
blueprint/sh.py \
/usr/lib/python2.4/site-packages/blueprint/
install -d /usr/lib/python2.4/site-packages/blueprint/backend/
install -m644 \
blueprint/backend/apt.py \
blueprint/backend/files.py \
blueprint/backend/gem.py \
blueprint/backend/**init**.py \
blueprint/backend/php.py \
blueprint/backend/pypi.py \
blueprint/backend/sources.py \
/usr/lib/python2.4/site-packages/blueprint/backend/
PYTHONPATH=/usr/lib/python2.4/site-packages python -mcompileall \
/usr/lib/python2.4/site-packages/blueprint
Listing /usr/lib/python2.4/site-packages/blueprint ...
Compiling /usr/lib/python2.4/site-packages/blueprint/**init**.py ...
Listing /usr/lib/python2.4/site-packages/blueprint/backend ...
Compiling /usr/lib/python2.4/site-packages/blueprint/backend/**init**.py ...
Compiling /usr/lib/python2.4/site-packages/blueprint/backend/apt.py ...
Compiling /usr/lib/python2.4/site-packages/blueprint/backend/files.py ...
File "/usr/lib/python2.4/site-packages/blueprint/backend/files.py", line 265
return os.path.isdir(pathname) if dir_only else True
^
SyntaxError: invalid syntax

Compiling /usr/lib/python2.4/site-packages/blueprint/backend/gem.py ...
Compiling /usr/lib/python2.4/site-packages/blueprint/backend/php.py ...
Compiling /usr/lib/python2.4/site-packages/blueprint/backend/pypi.py ...
Compiling /usr/lib/python2.4/site-packages/blueprint/backend/sources.py ...
File "/usr/lib/python2.4/site-packages/blueprint/backend/sources.py", line 40
except OSError as e:
^
SyntaxError: invalid syntax

Compiling /usr/lib/python2.4/site-packages/blueprint/chef.py ...
File "/usr/lib/python2.4/site-packages/blueprint/chef.py", line 114
except OSError as e:
^
SyntaxError: invalid syntax

Compiling /usr/lib/python2.4/site-packages/blueprint/context_managers.py ...
Compiling /usr/lib/python2.4/site-packages/blueprint/git.py ...
Compiling /usr/lib/python2.4/site-packages/blueprint/manager.py ...
Compiling /usr/lib/python2.4/site-packages/blueprint/puppet.py ...
File "/usr/lib/python2.4/site-packages/blueprint/puppet.py", line 161
except OSError as e:
^
SyntaxError: invalid syntax

Compiling /usr/lib/python2.4/site-packages/blueprint/sh.py ...
make: **\* [install-lib] Error 1

**Comment by rcrowley** [comment]
Python 2.4 is not currently supported.  #19 is tracking progress on that front.

**Comment by rcrowley** [comment]
I've just opened a topic on the mailing list explaining that Python 2.4 support will not be merged.  https://groups.google.com/forum/#!topic/blueprint-dev/mjLKgxl2vJw
