### ISSUE TITLE
CentOS release 5.5 (Final) is not blueprinting third party repositories

### ISSUE THREAD

**Issue by glennaaldering** [devstructure/blueprint#34]
Many thanks to all the updates of last month! Blueprint seems to be working really good on CentOS 5.5!

On a blueprinted system i have the EPEL and RPMFORGE repositorys enabled. The repositorys are not being restored on a new empty server. Im getting errors when running the shell bootstrap regarding the GPG key and packages which cannot be found in the default CentOS repository.

It would be really nice if it is somehow possible to automate the blueprinting of other repositories as well because right now i have to manually install all the extra repositories and then run bootstrap.sh

The following command returns all available repositories: yum repolist

**Comment by rcrowley** [comment]
Where are the "installed" RPM repositories stored?  On Debian and descendants, `/etc/apt/sources.list` and `/etc/apt/sources.list.d/*.list` contain the `deb` and `deb-src` lines that define the Debian archive(s) in use.

I'm hoping for a set of files to extract rather than having to special-case runs of `yum repolist` all the time.

**Comment by glennaaldering** [comment]
I think it should be /etc/yum.repos.d/

On 05/21/2011 08:36 PM, rcrowley wrote:

> Where are the "installed" RPM repositories stored?  On Debian and descendants, `/etc/apt/sources.list` and `/etc/apt/sources.list.d/*.list` contain the `deb` and `deb-src` lines that define the Debian archive(s) in use.
> 
> I'm hoping for a set of files to extract rather than having to special-case runs of `yum repolist` all the time.>

## 

Met vriendelijke groet / Best regards,

Glenn Aaldering

True
Cooperatiehof 16a
NL-1073 JR Amsterdam

T: +31 (0)20 305 97 50
F: +31 (0)20 305 97 51
E: glenn@true.nl
W: http://www.true.nl

**Comment by rcrowley** [comment]
Am I right in assuming that you've installed EPEL via an RPM?  This seems from my research to be how Yum repositories are typically managed.  Does the EPEL RPM appear in your blueprint?

**Comment by rcrowley** [comment]
It's possible to use `blueprintignore`(5) to include the EPEL files in your blueprint.  After running `rpm -ql epel-release` I added these lines to `~/.blueprintignore` and created a blueprint:

```
!/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL
!/etc/yum.repos.d/epel-testing.repo
!/etc/yum.repos.d/epel.repo
```

When the blueprint is applied, it will create and populate those files before installing any RPMs.

This is definitely only a workaround but it's better than nothing.

**Comment by glennaaldering** [comment]
On 05/26/2011 12:58 AM, rcrowley wrote:

> Am I right in assuming that you've installed EPEL via an RPM?  This seems from my research to be how Yum repositories are typically managed.  Does the EPEL RPM appear in your blueprint?

Yes thats correct, i install it via RPM, its the easyest way to achieve 
this in centos/redhat. Im not exactly sure if the EPEL package appears 
in my blueprint, do you want me to check that? I wouldt need to boot my 
blueprint test machines then?

Here's how i install 32 bit versions:

rpm -Uvh 
http://download.fedora.redhat.com/pub/epel/5/i386/epel-release-5-4.noarch.rpm
yum update

More info can be found here about the repository from fedora:

http://download.fedora.redhat.com/pub/epel/5/i386/repoview/epel-release.html

There is also other repositories like dag wiers which are quite commenly 
used: http://dag.wieers.com/rpm/FAQ.php#B2

rpm -Uhv 
http://apt.sw.be/redhat/el5/en/i386/rpmforge/RPMS/rpmforge-release-0.3.6-1.el5.rf.i386.rpm
yum update
[edit]

64 bit versions are like this in case its handy:

rpm -Uvh 
http://download.fedora.redhat.com/pub/epel/5/x86_64/epel-release-5-4.noarch.rpm
yum update

rpm -Uhv 
http://apt.sw.be/redhat/el5/en/x86_64/rpmforge/RPMS//rpmforge-release-0.3.6-1.el5.rf.x86_64.rpm
yum update

## 

Met vriendelijke groet / Best regards,

Glenn Aaldering

True
Cooperatiehof 16a
NL-1073 JR Amsterdam

T: +31 (0)20 305 97 50
F: +31 (0)20 305 97 51
E: glenn@true.nl
W: http://www.true.nl

**Comment by rcrowley** [comment]
The https://github.com/devstructure/blueprint/tree/yum-repos branch is available for testing a possible middle-ground solution to this issue.  Blueprint now specifically includes the Yum repository definitions and GPG public keys.

When applying a blueprint, these files are placed before packages are installed so subsequent `yum` calls will succeed, with one possible (likely?) exception: if the RPM that "installs" a Yum repository doesn't exist in that (or another) Yum repository will fail.  This issue does not occur with EPEL <del>but does occur with RPMforge</del> or RPMforge.

**Comment by glennaaldering** [comment]
Tested and works for rpmforge and epel repository. Great work!

[root@blueprint2centos ~]# rpm -qa |grep epel
[root@blueprint2centos ~]# rpm -qa |grep rpmforge

[root@blueprint2centos ~]# sh bootstrap.sh

[root@blueprint2centos ~]# rpm -qa |grep epel
epel-release-5-4
[root@blueprint2centos ~]# rpm -qa |grep rpmforge
rpmforge-release-0.5.2-2.el5.rf
