### ISSUE TITLE
mongodb config file modification not detected in Ubuntu 10.10

### ISSUE THREAD

**Issue by zenmatt** [devstructure/blueprint#35]
Mongodb package installed via apt-get, but modified config file not detected by blueprint, see below:

rm /etc/init/mongodb.conf
cat > /etc/init/mongodb.conf << EOF
description "MongoDB Config Server"

pre-start script
    mkdir -p /data/db/mongodb/
    chown -R mongodb:mongodb /data
end script

start on startup
stop on shutdown

exec start-stop-daemon --start --quiet --chuid mongodb --exec  /usr/bin/mongod -- --configsvr --dbpath /data/db/mongodb --logpath /data/db/mongodb.log --logappend
EOF

**Comment by rcrowley** [comment]
Are you ignoring the file or directory in `~/.blueprintignore`?  Is the content exactly the same as what's packaged?
