### ISSUE TITLE
Error installing man pages

### ISSUE THREAD

**Issue by drnic** [devstructure/blueprint#4]
<pre>$ sudo make install
...

install -d /usr/local/share/man/man1
install -m644 \
        man/man1/blueprint.1 \
        man/man1/blueprint-apply.1 \
        man/man1/blueprint-create.1 \
        man/man1/blueprint-destroy.1 \
        man/man1/blueprint-list.1 \
        man/man1/blueprint-show.1 \
        /usr/local/share/man/man1/
install: man/man1/blueprint.1: No such file or directory
make: *** [install-man] Error 71
</pre>

**Comment by rcrowley** [comment]
This is a bug.  For now `gem install ronn && make man` or removing `install-man` from the install prerequisites will satisfy it.  I will begin storing the rendered roff man pages in Git so users don't need Ronn to install.

**Comment by rcrowley** [comment]
Store rendered manual pages in Git.

This closed by bf864b1d4c806cece7b079fa366f58f1e174be1e and lowers the barriers to newcomers (since they will no longer need Ronn, RubyGems, and Ruby).
