### ISSUE TITLE
permissions error causes blueprint-create to fail

### ISSUE THREAD

**Issue by jcran** [devstructure/blueprint#43]
Ran into this error when running the command 'blueprint-create test'

```
jcran@disko:~/Desktop/blueprint/blueprint$ blueprint-create test
# [blueprint] searching for APT packages to exclude
No packages found matching installation-report.
No packages found matching linux-generic-pae.
No packages found matching linux-server.
# [blueprint] caching excluded APT packages
# [blueprint] searching for Yum packages to exclude
# [blueprint] searching for APT packages
# [blueprint] searching for configuration files
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-create", line 53, in <module>
    b = blueprint.Blueprint(name=name, create=True)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/__init__.py", line 66, in __init__
    getattr(backend, funcname)(self)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/backend/files.py", line 90, in files
    for filename in filenames]]
OSError: [Errno 13] Permission denied: '/etc/ld.so.conf.d/rapid7-nexpose.conf'
```

In trying to access this file, i received a 'permission denied' error, despite it being world-readable:

```
jcran@disko:~/Desktop/blueprint$ ls -latr /etc/ld.so.conf.d/rapid7-nexpose.conf
'ls: cannot access /etc/ld.so.conf.d/rapid7-nexpose.conf: Permission denied

jcran@disko:~/Desktop/blueprint$ sudo ls -latr /etc/ld.so.conf.d/rapid7-nexpose.conf
-rw-r--r-- 1 root root 35 2010-12-21 12:45 /etc/ld.so.conf.d/rapid7-nexpose.conf
```

**Comment by jcran** [comment]
I would consider this a config error on my side, but i wouldn't expect blueprint-create to completely fall over when it can't read the file.

**Comment by rcrowley** [comment]
You're right that this is a bug in Blueprint: it should never crash because of a permission mismatch.

I suspect that on your system `/etc/ld.so.conf.d` may not be world readable/executable.  Could you verify the mode is something like 755 and not something like 750?

Thanks!

**Comment by jcran** [comment]
you nailed it, the parent directory is readable, but not executable. 

root@disko:/etc/ld.so.conf.d# ls -latr
total 44
..
[snip]
..
drw-r--r--   2 root root  4096 2011-01-18 10:44 .
drwxr-xr-x 195 root root 12288 2011-05-23 13:47 ..
root@disko:/etc/ld.so.conf.d#
