### ISSUE TITLE
Write git output to stdout when throwing a git error

### ISSUE THREAD

**Issue by jbarciauskas** [devstructure/blueprint#44]
I had an issue where I had created a fresh copy of a VM in our environment that I was going to blueprint, and I kept getting an GitError: 1 message. I changed the output of subprocess to go to stdout rather than stderr and saw the issue was that I hadn't set my git ident and git was throwing an error saying empty ident not allowed.  Blueprint should capture and display this output on an error.

**Comment by rcrowley** [comment]
You're right.

**Comment by jbarciauskas** [comment]
Thanks for the quick response, I'm just leaving it as outputting to stdout rather than stderr, not sure if you want to do something else here.

**Comment by rcrowley** [comment]
Could you paste the change you made here (or send a pull request), please?  I see two places where there's potential to log this stuff but I believe it's setup to do the right thing already.

**Comment by jbarciauskas** [comment]
You're right, the issue is more subtle - if you run blueprint as sudo on the first run, the repo directory is created with root ownership.  In this case the output is simply:

Traceback (most recent call last):
  File "/usr/local/bin/blueprint-create", line 54, in <module>
    b.commit(options.message or '')
  File "/opt/lib/python2.6/site-packages/blueprint/**init**.py", line 210, in commit
    git.init()
  File "/opt/lib/python2.6/site-packages/blueprint/git.py", line 40, in init
    raise GitError(p.returncode)
blueprint.git.GitError: 1

Rather than the full output explaining the git error.  I'm somewhat mystified by why this is, sys.stderr must be pointing someplace unexpected in this case?  

To reproduce consistently:

rm -rf .blueprints.git
comment out the name and email lines in .gitconfig

e.g. 

[user]
;       email = jbarciauskas@bluestatedigital.com
;       name = Joel Barciauskas

then run: sudo blueprint create temp -S

**Comment by jbarciauskas** [comment]
This seems to fix it:

https://gist.github.com/989746

**Comment by rcrowley** [comment]
This seems to be an extra condition related to #40, which was (not quite) fixed in e3d55902f1941e3db8404143a58a4714326531ea.  The patch you provided will work but has the side effect of losing root privileges for the remainder of the process life.  I'll be back in a moment with a full fix.
