### ISSUE TITLE
Allow creating source tarballs of arbitrary directories

### ISSUE THREAD

**Issue by rcrowley** [devstructure/blueprint#46]
Graphite installs in `/opt` and there's basically nothing you can do about it.  To properly include such installations, we need to be able to tell `blueprint-create` to grab that extra directory.

**Comment by jbarciauskas** [comment]
I was actually going to open an issue on this as well, as a number of our systems use arbitrary /home directories rather than /usr/local, etc.

**Comment by rcrowley** [comment]
It's a delicate issue, as I don't want to encourage using blueprints to manage data.  Grabbing dotfiles from home directories doesn't seem like a bad thing to enable, either.

**Comment by jbarciauskas** [comment]
How do you define "managing data" as opposed to configuration? From chef's perspective, you describe everything you need to make the server able to fulfill the role it's designated for, which often includes a variety of directories with source files scattered about.  In our case, as I mentioned we use /home directories admittedly in instances where we probably shouldn't, but in order for us to make an accurate recipe we'll need to include the contents of particular home directories.  

It seems like we could reuse most of the usr/local code, with hooks for special handling, e.g. your rubygems exceptions, in the cases of certain directory names.

**Comment by rcrowley** [comment]
What you're describing is well within the realm I want to support.

I don't think Blueprint should be a useful tool for copying/replicating/backing up user-generated data, be it file uploads, databases, or anything else.

**Comment by rcrowley** [comment]
Merged into master.

**Comment by rcrowley** [comment]
See http://devstructure.github.com/blueprint/blueprintignore.5.html for details.
