### ISSUE TITLE
Mercurial support

### ISSUE THREAD

**Issue by silopolis** [devstructure/blueprint#48]
Hi,

First things first... this is an AMAZING project ! Not doubt it's about to become the very first package installed on my boxes from now on. Thanks a LOT for it.

Now the request :-P
As I already use etckeeper with Mercurial on my systems, because I tend to favor Python software over others where I can, and so Hg over other DVCSs, and because it would avoid me installing both Hg and Git on all my servers... It'd be great if Blueprint would also support Mercurial.

Hat down for this brilliant idea and thanks a lot again for coding and freeing it
Bests
JT

**Comment by zenmatt** [comment]
Thank you Silopolis, we really appreciate that!

Regarding Mercurial. In the immediate short term, support is unlikely. A bit further out, we can consider removing the Git dependency. This might be accomplished by no longer requiring Git or moving to a plugin architecture for the backend, so you could add support for another VCS. I hope this helps, let us know if you have any other feedback.
