### ISSUE TITLE
OverflowError: signed integer is greater than maximum

### ISSUE THREAD

**Issue by jbarciauskas** [devstructure/blueprint#49]
I get:

# [blueprint] searching for software built from source
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-create", line 56, in <module>
    b = blueprint.Blueprint(name=name, create=True)
  File "/opt/lib/python2.6/site-packages/blueprint/**init**.py", line 72, in **init**
    getattr(backend, funcname)(self)
  File "/opt/lib/python2.6/site-packages/blueprint/backend/sources.py", line 40, in sources
    os.lchown(dirpath2, s.st_uid, s.st_gid)
OverflowError: signed integer is greater than maximum

When running sudo blueprint create.  Presumably related to: http://bugs.python.org/issue1747858 as this is a 64-bit CentOS 4 system with python 2.6 built from source.  I worked around this by catching the OverflowError and just calling os.lchown(dirpath2, s.st_uid, -1) directly, not sure what the right solution overall is, maybe nothing.

**Comment by rcrowley** [comment]
Your diagnosis is spot on.

I think the right solution may be to first attempt to use the `os.lchown` system call wrapper from Python.  If that fails with `OverflowError` then log it and fork/exec `chown`(1).

**Comment by rcrowley** [comment]
I'm testing a patch on the `python-issue1747858` branch right now.  If you have a chance to test it, too, let me know.

**Comment by rcrowley** [comment]
I have been unable to reproduce the issue but have tested artificially that the patch works as intended.  Please verify that it solves your problem and I'll merge it into master for the 3.0.5 release.

**Comment by jbarciauskas** [comment]
Checking now, it's redoing the exclusion list for whatever reason

**Comment by jbarciauskas** [comment]
I can't seem to reproduce the issue either, although that's not incredibly surprising as I removed a bunch of stuff from /usr/local, though putting it back didn't seem to have any effect, there may have been some output generated that ended up in there and caused the issue.  Anyway, sorry, but seems to be working either way at the moment.
