### ISSUE TITLE
RHEL Support

### ISSUE THREAD

**Issue by kennethreitz** [devstructure/blueprint#5]
I _loathe_ configuration and setup on CentOS and the like, so this would be excellent to have. 

Are there plans for adding support for rpm based systems? Any pointers on where to start?

**Comment by rcrowley** [comment]
There is definitely support coming very soon.  We've been talking it out on the blueprint-users mailing list: https://groups.google.com/forum/#!topic/blueprint-users/siVbpJkLvtI.  Please jump in!

**Comment by deplorableword** [comment]
Great to see support coming for CentOS and RHEL

**Comment by rcrowley** [comment]
Preliminary Yum/RPM support is in master.  Please open bugs on any issues you see!
