### ISSUE TITLE
GitError raise with Git 1.5.5.6

### ISSUE THREAD

**Issue by enobrev** [devstructure/blueprint#59]
> git --version
> git version 1.5.5.6
> 
> blueprint create my-first-blueprint
> [blueprint] using cached blueprintignore rules
> [blueprint] searching for software built from source
> [blueprint] /usr/local/bin/python2.7 caused EXDEV - try running as root  // NOTE - i am
> [blueprint] searching for Ruby gems
> [blueprint] searching for Python packages
> [blueprint] searching for APT packages
> [blueprint] searching for Yum packages
> [blueprint] searching for configuration files
> [blueprint] searching for PEAR/PECL packages
> Traceback (most recent call last):
>   File "/usr/local/bin/blueprint-create", line 60, in <module>
>     b.commit(options.message or '')
>   File "/usr/local/lib/python2.7/site-packages/blueprint/**init**.py", line 238, in commit
>     git.init()
>   File "/usr/local/lib/python2.7/site-packages/blueprint/git.py", line 45, in init
>     raise GitError(p.returncode)
> blueprint.git.GitError: 129  

Upgrading Git resolved the issue.  I didn't see the requirement anywhere, so I figured I'd announce my confusion.

Thanks for being awesome.

**Comment by rcrowley** [comment]
Thanks for pointing out your confusion, @enobrev.  I've opened a separate bug #60 for the EXDEV issue, which was unrelated.  You were right that a Git upgrade was in order - we require 1.7.
