### ISSUE TITLE
Error while running blueprint create 

### ISSUE THREAD

**Issue by leenasn** [devstructure/blueprint#63]
Hi,

I followed the instructions mentioned in your readme to create a configuration file for my rails app.  But when I run the command _blueprint create -S my-conf_, it give the following error:

[blueprint] using cached blueprintignore rules
[blueprint] searching for software built from source
[blueprint] /usr/local caused EPERM - try running as root
[blueprint] searching for Yum packages
[blueprint] searching for PEAR/PECL packages
[blueprint] searching for Ruby gems
[blueprint] searching for configuration files
[blueprint] searching for APT packages
[blueprint] searching for Python packages
[blueprint] searching for service dependencies
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-create", line 61, in <module>
    b = blueprint.Blueprint(name=name, create=True)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/**init**.py", line 67, in **init**
    services.services(self)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/services.py", line 80, in services
    b.walk_services(service=service)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/**init**.py", line 512, in walk_services
    self.walk_services(managername, **kwargs)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/**init**.py", line 522, in walk_services
    callable(manager, service)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/services.py", line 78, in service
    b.walk_service_files(manager, service, service_file=service_file)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/**init**.py", line 540, in walk_service_files
    for pathname in deps['files']:

Please let me know what I am missing.

Thanks,
Leena

**Comment by rcrowley** [comment]
Hi Leena!  This obviously shouldn't be happening but I'm having trouble reproducing the issue.  Was there another line to the output that mentions something like `KeyError` or `ValueError`?

**Comment by leenasn** [comment]
No, there were no other errors. I've tried it on 2 different machines, and
got the same result. Right now I don't have access to those machines, as
those are in my office.

The configurations of the machine are:
- Ubuntu 10.04
- Uses RVM (I've tried with both ruby 1.9.1 and 1.9.2 under RVM)

The steps I followed are:
- Installed Bluepring using the instructions as mentioned under the
  section _From source on Debian, Ubuntu, and Fedora_
- Ran the command _blueprint create -S my-conf_ from my rails app
  directory.

I could see the same being mentioned in the tutorial also. I also tried it
for a Sinatra app, and the same error.

Hope this helps.

Thanks,
Leena

**Comment by rcrowley** [comment]
Could I trouble you to run the [leenasn](https://github.com/devstructure/blueprint/tree/leenasn) branch when you get the time?  It will print a bit more debugging info that'll help me figure out what's going wrong.  If you could please paste that here I'll see what I can do.

**Comment by leenasn** [comment]
I ran it with the the branch, and here is the output.

<pre><code>[blueprint] caching excluded APT packages
[blueprint] searching for Yum packages to exclude
[blueprint] searching for software built from source
[blueprint] /usr/local caused EPERM - try running as root
[blueprint] searching for Yum packages
[blueprint] searching for PEAR/PECL packages
[blueprint] searching for Ruby gems
[blueprint] searching for configuration files
[blueprint] searching for APT packages
[blueprint] searching for Python packages
[blueprint] searching for service dependencies
{'files': set([u'/etc/apache2/apache2.conf',
               u'/etc/apache2/httpd.conf',
               u'/etc/apache2/mods-available/proxy.conf',
               u'/etc/apache2/mods-enabled/auth_basic.load',
               u'/etc/apache2/mods-enabled/authn_file.load',
               u'/etc/apache2/mods-enabled/authz_default.load',
               u'/etc/apache2/mods-enabled/authz_groupfile.load',
               u'/etc/apache2/mods-enabled/authz_host.load',
               u'/etc/apache2/mods-enabled/authz_user.load',
               u'/etc/apache2/mods-enabled/cgi.load',
               u'/etc/apache2/mods-enabled/env.load',
               u'/etc/apache2/mods-enabled/headers.load',
               u'/etc/apache2/mods-enabled/php5.conf',
               u'/etc/apache2/mods-enabled/php5.load',
               u'/etc/apache2/mods-enabled/proxy_balancer.load',
               u'/etc/apache2/mods-enabled/proxy_http.load',
               u'/etc/apache2/mods-enabled/rewrite.load',
               u'/etc/apache2/ports.conf',
               u'/etc/apache2/server.crt',
               u'/etc/apache2/server.csr',
               u'/etc/apache2/server.key',
               u'/etc/apache2/server.pem',
               u'/etc/apache2/sites-available/caldav',
               u'/etc/apache2/sites-available/default',
               u'/etc/apache2/sites-available/default_orig',
               u'/etc/apache2/sites-available/elixir',
               u'/etc/apache2/sites-available/ical',
               u'/etc/apache2/sites-available/ical_admin',
               u'/etc/apache2/sites-available/pmp',
               u'/etc/apache2/sites-available/pmp_kut',
               u'/etc/apache2/sites-available/pmp_wbur',
               u'/etc/apache2/sites-available/pmp_widget',
               u'/etc/apache2/sites-available/qa-caldav',
               u'/etc/apache2/sites-available/qa-caldav-admin',
               u'/etc/apache2/sites-available/widget',
               u'/etc/apache2/sites-enabled/000-default',
               u'/etc/apache2/sites-enabled/elixir',
               u'/etc/cron.daily/google-chrome',
               u'/etc/default/console-setup',
               u'/etc/default/google-chrome',
               u'/etc/default/grub',
               u'/etc/default/locale',
               u'/etc/default/rcS']),
 'packages': defaultdict(<type 'set'>, {'apt': set(['apache2.2-common'])})}
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-create", line 61, in <module>
    b = blueprint.Blueprint(name=name, create=True)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/__init__.py", line 75, in __init__
    services.services(self)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/services.py", line 80, in services
    b.walk_services(service=service)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/__init__.py", line 520, in walk_services
    self.walk_services(managername, **kwargs)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/__init__.py", line 530, in walk_services
    callable(manager, service)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/services.py", line 78, in service
    b.walk_service_files(manager, service, service_file=service_file)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/__init__.py", line 550, in walk_service_files
    for pathname in deps['files']:
RuntimeError: Set changed size during iteration</code></pre>


Hope this helps.

Thanks,
Leena

**Comment by rcrowley** [comment]
That debug run did the trick, thank you.  The master branch is updated with a fix for this problem.  If you run into any troubles, please let me know.

Thanks again,

Richard

**Comment by leenasn** [comment]
Thanks a lot Richard, it worked.

Leena
