### ISSUE TITLE
Suboptimal behavior with etckeeper

### ISSUE THREAD

**Issue by al2o3cr** [devstructure/blueprint#7]
Not sure if this is a bug or simply needs to be documented, but using blueprint on a server with etckeeper installed creates a sizable amount of noise when the entire /etc/.git directory is dumped. It might be valuable to add that directory to the default blueprintignore.

**Comment by rcrowley** [comment]
You're right.

**Comment by rcrowley** [comment]
This will be fixed by #10, which I intend to merge as soon as I hear back from mrud.

**Comment by rcrowley** [comment]
Ignore /etc/.git (used by etckeeper) per default, Closed by 821478fd66d20b65d3b66b64194e3edf0d0b4bb3.
