### ISSUE TITLE
Not working with Amazon EC2 

### ISSUE THREAD

**Issue by leenasn** [devstructure/blueprint#71]
Hi,

I setup blueprint in our Amazon EC2 server (micro instance) and installation went fine. But when I run the command _blueprint create_, it gave me the following error:

```
# [blueprint] caching excluded APT packages
# [blueprint] searching for Yum packages to exclude
# [blueprint] searching for APT packages
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-create", line 61, in <module>
    b = blueprint.Blueprint(name=name, create=True)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/__init__.py", line 73, in __init__
    getattr(backend, funcname)(self)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/backend/apt.py", line 39, in apt
    manager, service = util.parse_service(line.rstrip())
  File "/usr/local/lib/python2.6/dist-packages/blueprint/util.py", line 68, in parse_service
    open(pathname).read()):
IOError: [Errno 2] No such file or directory: '/etc/init/cloud-config-mounts.conf'
```

I tried it with 2 different instances, and in both it gave the same error. Please let me know whether I am missing something.

Thanks,
Leena

**Comment by rcrowley** [comment]
Hi @leenasn,

Does `/etc/init/cloud-config-mounts.conf` exist on these machines?  What does the command `dpkg-query -S /etc/init/cloud-config-mounts.conf` say?

Thanks for reporting this.  The patch above will properly handle the exception you've encountered but I'm curious about the above commands because maybe there's something even more intelligent Blueprint can do in this scenario.

**Comment by leenasn** [comment]
The file `/etc/init/cloud-config-mounts.conf` does not exist. And the command `dpkg-query -S /etc/init/cloud-config-mounts.conf` says: `cloud-init: /etc/init/cloud-config-mounts.conf`. Hope this helps.

Thanks,
Leena

**Comment by leenasn** [comment]
With the patch you had given, it ran successfully.

Thanks,
Leena
