### ISSUE TITLE
NameError: global name 'yum_packages' is not defined

### ISSUE THREAD

**Issue by ewanleith** [devstructure/blueprint#83]
After running the basic installation instructions on Ubuntu 10.04 with the latest code, running "blueprint create test" generates the following error:

blueprint create standard
[blueprint] using cached blueprintignore rules
[blueprint] searching for configuration files
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-create", line 61, in <module>
    b = blueprint.Blueprint(name=name, create=True)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/**init**.py", line 93, in **init**
    getattr(backend, funcname)(self)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/backend/files.py", line 778, in files
    *yum_packages)
NameError: global name 'yum_packages' is not defined

**Comment by ewanleith** [comment]
Looks like this has been caused by commit 67ee17a:

https://github.com/devstructure/blueprint/commit/67ee17af517ea1e457f783e0c8be62c235f52d8d#blueprint/backend/files.py

which has removed these 2 lines
-            yum_packages = _rpm_qf(pathname)
-            packages = apt_packages + yum_packages

But has left the problem reference at the end

**Comment by rcrowley** [comment]
Sorry about this, @ewanleith.

**Comment by ewanleith** [comment]
Thanks @rcrowley, excellent tool by the way!
