### ISSUE TITLE
keyring.gpg 403 error

### ISSUE THREAD

**Issue by tmslnz** [devstructure/blueprint#85]
Trying to copy http://packages.devstructure.com/keyring.gpg
Server responds with a 403 Forbidden. Could you please fix it? I'd like to install via package manager if possible.

**Comment by trivoallan** [comment]
Same problem here.

**Comment by rcrowley** [comment]
Fixed.  I'm sorry, guys.  This is a bug in Freight, the package we use to maintain that Debian archive.

**Comment by tmslnz** [comment]
Thanks dude.
